# Generated by Django 4.2 on 2023-04-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_category_alter_image_owner_listing_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
    ]
