# Generated by Django 4.2 on 2023-04-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_alter_message_date_time_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.CharField(default='bad', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_time_sent',
            field=models.BigIntegerField(),
        ),
    ]
