# Generated by Django 4.2 on 2023-04-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_review_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='location',
            name='long',
            field=models.FloatField(default='0'),
        ),
    ]
