# Generated by Django 4.2 on 2023-04-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_location_lat_location_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pic',
            field=models.URLField(default='https://media.istockphoto.com/id/1074273158/vector/person-gray-photo-placeholder-man.jpg?s=612x612&w=0&k=20&c=OcUd-R2-sPpl33QVLuY9haUUAuvdlQK8XrkciaNFLO8='),
        ),
        migrations.AddField(
            model_name='customuser',
            name='saved',
            field=models.ManyToManyField(to='market.listing'),
        ),
    ]
