# Generated by Django 4.2 on 2023-04-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_customuser_pic_customuser_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='pic',
            new_name='image',
        ),
    ]
